# Generated by Django 4.2.5 on 2023-09-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('limite_hospedes', models.PositiveIntegerField()),
                ('quantidade_banheiros', models.PositiveIntegerField(verbose_name=2)),
                ('aceita_animais_estimacao', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_ativacao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
