# Generated by Django 4.2.5 on 2023-09-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.PositiveIntegerField(default=230915351643, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('numero_hospedes', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anuncios.anuncio')),
            ],
        ),
    ]
