# Generated by Django 4.2.5 on 2023-09-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plataforma', models.CharField(max_length=255)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imoveis.imovel')),
            ],
        ),
    ]
