# Generated by Django 4.2.5 on 2023-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
